#!/usr/bin/env bash

# Load the monero-config.json file
EXPORTS_APP_DIR="${UMBREL_ROOT}/app-data/monero"
MONERO_APP_CONFIG_FILE="${EXPORTS_APP_DIR}/data/app/monero-config.json"
PYYAML_SCRIPT="${EXPORTS_APP_DIR}/scripts/docker_gen.py"
MONERO_DOCKER_COMPOSE_FILE="${EXPORTS_APP_DIR}/docker-compose.yml"
BTCPAY_DOCKER_COMPOSE_FILE="${UMBREL_ROOT}/app-data/btcpay-server/docker-compose.yml"

#Check if  btcpay is enabled
if [[ -f "$MONERO_APP_CONFIG_FILE" ]]; then
	export MONERO_BTCPAY_ENABLED=$(jq -r '.btcpayserver' "${MONERO_APP_CONFIG_FILE}")
fi

if [ "$MONERO_BTCPAY_ENABLED" == "true" ]; then
	python3 ${PYYAML_SCRIPT} add monero ${BTCPAY_DOCKER_COMPOSE_FILE}
	changed=$?
	python3 ${PYYAML_SCRIPT} add btcpay ${BTCPAY_DOCKER_COMPOSE_FILE}
elif [ "$MONERO_BTCPAY_ENABLED" == "false"  ]; then
	python3 ${PYYAML_SCRIPT} remove monero ${BTCPAY_DOCKER_COMPOSE_FILE}
	changed=$?
	python3 ${PYYAML_SCRIPT} remove btcpay ${BTCPAY_DOCKER_COMPOSE_FILE}
fi

# if changed, restart btcpay
if [ "$changed" -eq 1 ]; then
	# check if umbreld exists, otherwise use the old method
	if command -v umbreld &> /dev/null; then
		umbreld client apps.restart.mutate --appId btcpay-server

		# print error message to check if this works
		echo "App: ${APP_ID} - Restarting BTCPay Server via new method..."
		umbreld client apps.restart.mutate --appId monero
	else
		/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script restart btcpay-server
		# print error message to check if this works
		echo "App: ${APP_ID} - Restarting BTCPay Server via old method..."
		/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script restart monero
	fi
fi

# Delay booting Monero until the RPC and P2P Tor Hidden Services are ready

HIDDEN_SERVICE_FILE="${TOR_DATA_DIR}/app-${APP_ID}-rpc/hostname"

if [[ -f "${HIDDEN_SERVICE_FILE}" ]]; then
	exit
fi

#check Umbrel OS version and start monerod and tor using the correct method
if [ -f /usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script ]; then
	/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script compose "${APP_ID}" up --detach monerod
	/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script compose "${APP_ID}" up --detach tor

echo "App: ${APP_ID} - Generating Tor Hidden Service..."

for attempt in $(seq 1 100); do
	if [[ -f "${HIDDEN_SERVICE_FILE}" ]]; then
		echo "App: ${APP_ID} - Hidden service file created successfully!"
		break
	fi
	sleep 0.1
done

if [[ ! -f "${HIDDEN_SERVICE_FILE}" ]]; then
	echo "App: ${APP_ID} - Hidden service file wasn't created"
fi