#!/usr/bin/env bash

# Load the monero-config.json file
MONERO_APP_CONFIG_FILE_DEFAULT="${UMBREL_ROOT}/app-data/monero/data/app/monero-config.json"
MONERO_APP_CONFIG_FILE="${EXPORTS_APP_DIR}/data/app/monero-config.json"
PYYAML_SCRIPT="${EXPORTS_APP_DIR}/scripts/docker_gen.py"
MONERO_DOCKER_COMPOSE_FILE="${EXPORTS_APP_DIR}/docker-compose.yml"
BTCPAY_DOCKER_COMPOSE_FILE="${UMBREL_ROOT}/app-data/btcpay-server/docker-compose.yml"

#Check if  btcpay is enabled
if [[ -f "$MONERO_APP_CONFIG_FILE" ]]; then
	export MONERO_BTCPAY_ENABLED=$(jq -r '.btcpayserver' "${MONERO_APP_CONFIG_FILE}")
	echo "MONERO_BTCPAY_ENABLED: ${MONERO_BTCPAY_ENABLED}"
fi

if [ "$MONERO_BTCPAY_ENABLED" == "true" ]; then
	python3 ${PYYAML_SCRIPT} add monero ${MONERO_DOCKER_COMPOSE_FILE}
	changed=$?
	# jq '.btcpayserver_install="false"' ${MONERO_APP_CONFIG_FILE} > temp.json && mv temp.json ${MONERO_APP_CONFIG_FILE}
	python3 ${PYYAML_SCRIPT} add btcpay ${BTCPAY_DOCKER_COMPOSE_FILE}
elif [ "$MONERO_BTCPAY_ENABLED" == "false"  ]; then
	python3 ${PYYAML_SCRIPT} remove monero ${MONERO_DOCKER_COMPOSE_FILE}
	changed=$?
	python3 ${PYYAML_SCRIPT} remove btcpay ${BTCPAY_DOCKER_COMPOSE_FILE}
fi
#print changed
echo "Changed: ${changed}"
# if changed, restart btcpay
if [ "$changed" -eq 1 ]; then
	# if old Umbrel OS version, restart btcpay using the old method
	if [ -f /usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script ]; then
		/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script restart btcpay-server
		# print error message to check if this works
		echo "App: ${APP_ID} - Restarting BTCPay Server via old method..."
	else
		umbreld client apps.restart.mutate --appId btcpay-server
		# print error message to check if this works
		echo "App: ${APP_ID} - Restarting BTCPay Server via new method..."
	fi
fi

# Delay booting Monero until the RPC and P2P Tor Hidden Services are ready

HIDDEN_SERVICE_FILE="${TOR_DATA_DIR}/app-${APP_ID}-rpc/hostname"

if [[ -f "${HIDDEN_SERVICE_FILE}" ]]; then
	exit
fi

#check Umbrel OS version and start monerod and tor using the correct method
if [ -f /usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script ]; then
	/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script compose "${APP_ID}" up --detach monerod
	/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script compose "${APP_ID}" up --detach tor
else
	/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script compose "${APP_ID}" up --detach monerod
	/usr/local/lib/node_modules/umbreld/source/modules/apps/legacy-compat/app-script compose "${APP_ID}" up --detach tor
fi

echo "App: ${APP_ID} - Generating Tor Hidden Service..."

for attempt in $(seq 1 100); do
	if [[ -f "${HIDDEN_SERVICE_FILE}" ]]; then
		echo "App: ${APP_ID} - Hidden service file created successfully!"
		break
	fi
	sleep 0.1
done

if [[ ! -f "${HIDDEN_SERVICE_FILE}" ]]; then
	echo "App: ${APP_ID} - Hidden service file wasn't created"
fi