version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tautulli_web_1
      APP_PORT: 8181

  web:
    image: linuxserver/tautulli:2.14.3@sha256:05521bf5fbab6d9297fed5ae8525b4ff24dec3773bce40c0d0b831a8708a13e2
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000