version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: firefly-iii-importer_importer_1
      APP_PORT: 8080

  importer:
    image: fireflyiii/data-importer:version-1.5.5@sha256:e78e413679ac92d721aa9ee8e0b558e7ad1126f8ec46a079b2af4b6a07830ade
    restart: on-failure
    environment:
      # firefly-iii container:
      - FIREFLY_III_URL=http://firefly-iii_server_1:8080
      - VANITY_URL=http://${DEVICE_DOMAIN_NAME}:30009