services:
  app_proxy:
    environment:
      APP_HOST: navidrome_server_1
      APP_PORT: 4533
      PROXY_AUTH_ADD: "false"

  server:
    image: deluan/navidrome:0.53.2@sha256:5e0c2ada777241a735483b79e9699edafa9dd26469cb1c4e8d4dbf4da9bc5820
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music