version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: calibre-web_server_1
      APP_PORT: 8083

  server:
    image: linuxserver/calibre-web:0.6.22@sha256:49660a8890e2e4356cbc4b8874ff5ad1ebc40f647fdb2419fc289700affebcf0
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/books:/books
    restart: on-failure