version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jackett_server_1
      APP_PORT: 9117
      PROXY_AUTH_WHITELIST: "/api/* /dl/*"

  server:
    image: linuxserver/jackett:0.22.411@sha256:cecdf933996f904e43c2b4e43db887e881b47e6ac340043e5667105c03bc7cbd
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000