version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: librespeed_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/librespeed/speedtest:5.4.0@sha256:98ddbdd5783165f37642458a40864899b09c439cc77f9d878a1e1833afe9256d
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure