version: "3.7"

services:
   app_proxy:
      environment:
         APP_HOST: minio_web_1
         APP_PORT: 9011
         PROXY_AUTH_ADD: "false"

   web:
      image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z@sha256:7d80fd232a2f7108aa6f133fcfe5fade3f1626d92d31ae1318076e7aa61928a2
      restart: on-failure
      user: "1000:1000"
      stop_grace_period: 1m
      ports:
         # MinIO Api Server Port
         - "9010:9000"
      command: ["server", "/data"]
      volumes:
         - ${APP_DATA_DIR}/data/minio:/data
      environment:
         MINIO_ROOT_USER: "umbrel"
         MINIO_ROOT_PASSWORD: "$APP_PASSWORD"
         MINIO_CONSOLE_ADDRESS: ":9011"