version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: metube_metube_1
      APP_PORT: 8081

  metube:
    image: ghcr.io/alexta69/metube:2024-07-26@sha256:5b690482ebf6c674101f6e111d6035e3d30fc102af01a0b62482aca684111942
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/metube:/downloads