version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: syncthing_server_1
      APP_PORT: 8384

  server:
    image: syncthing/syncthing:1.27.9@sha256:9f16c4aaf678add90a85bd53e324bfbb57d1e704e6a07b54c446e4a67e590dbf
    restart: on-failure
    stop_grace_period: 1m
    hostname: umbrel
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp