version: "3.7"

services:
  server:
    image: esphome/esphome:2024.9.1@sha256:b9a2f15a8aa85d933f8eeb28a34010eb2274c2a24a96858922b65a3402f1dc44
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure