version: "3.7"

services:
  server:
    image: esphome/esphome:2024.7.2@sha256:e6e98daf807a3cdf33914d725cde3d87ef4a935cdc334bed1f7a266fc12df52b
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure